// Auto-generated by scripts/hash-json.ts
export const DATA_MANIFEST = {
  "conjugations": "conjugations.2049d6c6.json.gz",
  "options": "options.30a64518.json.gz",
  "pronouns": "pronouns.0f1c1999.json.gz",
  "verbs": "verbs.24d68101.json.gz",
  "en": "en.a83d31cf.json",
  "fr": "fr.0662e360.json"
} as const;
